global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432', 'tests-db:5432']

  - job_name: 'identity-service'
    static_configs:
      - targets: ['identity:5215']

  - job_name: 'test-service'
    static_configs:
      - targets: ['tests:5068']

  - job_name: 'postgres-identity'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'postgres-tests'
    static_configs:
      - targets: ['tests-postgres-exporter:9187']